### ISSUE TITLE
[BUG] ImportError OrderedDict

### ISSUE THREAD

**Issue by johannes-graeter** [Textualize/rich#2150]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/willmcgugan/rich/issues).

First: Thanks for your awesome project and the work you take to make devs lifes better :)!
**Describe the bug**

Some updates seem to have mixed up dependencies.
```bash
> rich README.md      
Traceback (most recent call last):
  File "/home/graeter/.local/bin/rich", line 5, in <module>
    from rich_cli.__main__ import run
  File "/home/graeter/.local/lib/python3.8/site-packages/rich_cli/__main__.py", line 7, in <module>
    from rich.console import Console, RenderableType
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/console.py", line 46, in <module>
    from ._log_render import FormatTimeCallable, LogRender
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/_log_render.py", line 5, in <module>
    from .text import Text, TextType
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/text.py", line 5, in <module>
    from rich.emoji import EmojiVariant
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/emoji.py", line 4, in <module>
    from .jupyter import JupyterMixin
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/jupyter.py", line 4, in <module>
    from .segment import Segment
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/segment.py", line 19, in <module>
    from .cells import (
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/cells.py", line 6, in <module>
    from ._lru_cache import LRUCache
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/_lru_cache.py", line 8, in <module>
    from typing_extensions import OrderedDict
ImportError: cannot import name 'OrderedDict' from 'typing_extensions' (/home/graeter/.local/lib/python3.8/site-packages/typing_extensions.py)
```
Can you point me to a working configuration?
Up to now I used rich very happily and would miss it a lot ;)

**Platform**
- Ubuntu 20.04
- python 3.8.10
- pip 22.0.4
- zsh with starship

<details>
```
python -m rich.diagnose
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/diagnose.py", line 5, in <module>
    from rich.console import Console, get_windows_console_features
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/console.py", line 46, in <module>
    from ._log_render import FormatTimeCallable, LogRender
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/_log_render.py", line 5, in <module>
    from .text import Text, TextType
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/text.py", line 5, in <module>
    from rich.emoji import EmojiVariant
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/emoji.py", line 4, in <module>
    from .jupyter import JupyterMixin
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/jupyter.py", line 4, in <module>
    from .segment import Segment
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/segment.py", line 19, in <module>
    from .cells import (
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/cells.py", line 6, in <module>
    from ._lru_cache import LRUCache
  File "/home/graeter/.local/lib/python3.8/site-packages/rich/_lru_cache.py", line 8, in <module>
    from typing_extensions import OrderedDict
ImportError: cannot import name 'OrderedDict' from 'typing_extensions' (/home/graeter/.local/lib/python3.8/site-packages/typing_extensions.py)

pip freeze | grep rich
rich==12.1.0
rich-cli==1.6.1
rich-rst==1.1.7
```

</details>

**Comment by willmcgugan** [comment]
Can I see the output of `pip list`?

**Comment by johannes-graeter** [comment]
Sure thanks for the prompt reply! [pip_list.txt](https://github.com/Textualize/rich/files/8408735/pip_list.txt)

**Comment by willmcgugan** [comment]
Does `pip install typing-extensions==4.0.0` fix it?

**Comment by johannes-graeter** [comment]
indeed it does! after upgrading tensorflow I am now conflict free, thanks :)

**Comment by willmcgugan** [comment]
Great. I'll update the dependancy in Rich.
