### ISSUE TITLE
[BUG] console Console

### ISSUE THREAD

**Issue by Mahrkeenerh** [Textualize/rich#2222]
Running windows, python 3.10,

I literally just did: `pip install rich`

And then inside idle, run:

```
from rich.console import Console
console = Console()
console.print([1, 2, 3])
```

And I just get an error?
```
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    console.print([1, 2, 3])
  File "C:\Users\samue\AppData\Roaming\Python\Python310\site-packages\rich\console.py", line 1737, in print
    render_options = self.options.update(
  File "C:\Users\samue\AppData\Roaming\Python\Python310\site-packages\rich\console.py", line 1073, in options
    max_height=self.size.height,
  File "C:\Users\samue\AppData\Roaming\Python\Python310\site-packages\rich\console.py", line 1101, in size
    width, height = os.get_terminal_size()
ValueError: bad file descriptor
```

Am I missing something?

**Comment by UltraStudioLTD** [comment]
I opened #2223 discussion for this issue

**Comment by UltraStudioLTD** [comment]
> Please try 12.3.0
> 
> It shouldn't crash, but Idle doesn't support many features. You will get better results with Windows Terminal.

@willmcgugan, why do you use that method for terminal size detection?
