### ISSUE TITLE
[BUG] BlockingIOError: [Errno 11] write could not complete without blocking in console.py

### ISSUE THREAD

**Issue by plummm** [Textualize/rich#2492]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/willmcgugan/rich/issues).

I'm using rich console to update some table data, and then I received this BlockingIOError after a few hours running
```
Traceback (most recent call last):
  File "syzmorph/infra/console/interface.py", line 105, in run
    live.update(self.msg_dispatch(), refresh=True)
  File "/data3/xzou017/projects/SyzMorph/venv/lib/python3.7/site-packages/rich/live.py", line 216, in update
    self.refresh()
  File "/data3/xzou017/projects/SyzMorph/venv/lib/python3.7/site-packages/rich/live.py", line 240, in refresh
    self.console.print(Control())
  File "/data3/xzou017/projects/SyzMorph/venv/lib/python3.7/site-packages/rich/console.py", line 848, in __exit__
    self._exit_buffer()
  File "/data3/xzou017/projects/SyzMorph/venv/lib/python3.7/site-packages/rich/console.py", line 806, in _exit_buffer
    self._check_buffer()
  File "/data3/xzou017/projects/SyzMorph/venv/lib/python3.7/site-packages/rich/console.py", line 2016, in _check_buffer
    self.file.write(text)
BlockingIOError: [Errno 11] write could not complete without blocking
```

Edit this with a clear and concise description of what the bug.

Provide a minimal code example that demonstrates the issue if you can. If the issue is visual in nature, consider posting a screenshot.

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on?
Linux 

What terminal software are you using?
xterm & iterm2

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
```

```
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=182 ColorSystem.EIGHT_BIT>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = '256'                                                         │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'> │
│           height = 48                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=182, height=48),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=182,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=48,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=182, height=48)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 182                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭─── <class 'rich._windows.WindowsConsoleFeatures'> ────╮
│ Windows features available.                           │
│                                                       │
│ ╭───────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ ╰───────────────────────────────────────────────────╯ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
╰───────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': 'xterm-256color',      │
│     'COLORTERM': None,             │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': None,          │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Linux"
```

```
rich==12.5.1
```

If you're using Rich in a Jupyter Notebook, run the following snippet in a cell
and paste the output in your bug report.

```python
from rich.diagnose import report
report()
```

</details>

**Comment by willmcgugan** [comment]
This is unlikely to be an issue with Rich itself. The same thing would happen if you were to print at this point. You might want to research ERRNO 11 and its causes.
