### ISSUE TITLE
[BUG] display not updating or BlockingIOError when used with another library 

### ISSUE THREAD

**Issue by max-l** [Textualize/rich#2614]
I'm writing a console CLI app, that needs to respond to keyboard input. 

My app must run inside an SSH terminal, so the choice of libraries for responding to keyboard events is restricted.

I use this library : 

   https://github.com/ollipal/sshkeyboard

My underlying platform is : 
```
Python:  3.10.2
OS:  CentOS Linux 7 (Core)
uname -r 
  3.10.0-1160.76.1.el7.x86_64
```

It works great, except when I use it in an SSH session, in which case I run into one of two situations: 

#### 1 BlockingIOError

I get this systematicaly (in SSH terminals), if I use auto_refresh=False

```python
       def refresher_loop():
            with Live(auto_refresh=False) as live:
                  while not self.quit:
                      live.update(Panel(_create_table(), border_style="blue"), refresh=True))
                      time.sleep(3)
```
It crashes with: 
```

Traceback (most recent call last):
  File "/nfs3_ib/ip32-ib/openprot-pipelines/test-pred/DryPipe/dry_pipe/cli_screen.py", line 289, in update_screen
    live.update(Panel(l, border_style="blue"), refresh=True)
  File "/nfs3_ib/ip32-ib/openprot-pipelines/prod/venv/lib/python3.10/site-packages/rich/live.py", line 216, in update
    self.refresh()
  File "/nfs3_ib/ip32-ib/openprot-pipelines/prod/venv/lib/python3.10/site-packages/rich/live.py", line 239, in refresh
    with self.console:
  File "/nfs3_ib/ip32-ib/openprot-pipelines/prod/venv/lib/python3.10/site-packages/rich/console.py", line 869, in __exit__
    self._exit_buffer()
  File "/nfs3_ib/ip32-ib/openprot-pipelines/prod/venv/lib/python3.10/site-packages/rich/console.py", line 827, in _exit_buffer
    self._check_buffer()
  File "/nfs3_ib/ip32-ib/openprot-pipelines/prod/venv/lib/python3.10/site-packages/rich/console.py", line 2039, in _check_buffer
    self.file.write(text)
BlockingIOError: [Errno 11] write could not complete without blocking

```

#### 2 console NOT updating

if I use auto_refresh=True, there is no crash, but the console never updates :

```python
       def refresher_loop():
            with Live(auto_refresh=True) as live:
                  while not self.quit:
                      live.update(Panel(_create_table(), border_style="blue")))
                      time.sleep(3)
```

The refresher loop is run by a dedicated thread, it is started like this : 

```
       from sshkeyboard import listen_keyboard, stop_listening

       refresh_thread = Thread(target=refresher)
       refresh_thread.start()

       if LISTEN_KEYBOARD:
           listen_keyboard(on_press=lambda key: self.press(key))
```

note the call of listen_keyboard  in the main thread, from the sshkeyboard library. 
The problem describe does NOT happen LISTEN_KEYBOARD=False. 

It seems like the two libs are competing for write access and causing a deadlock, infinit wait, etc...

Note that they keyboard events are working when auto_refresh=True, so it seems that sshkeyboard might be obtaining an exclusive write lock on an underlying stream (stdout), and never releasing it.

The only stream locking related code I can find in sshkeyboard is : 

   https://github.com/ollipal/sshkeyboard/blob/main/src/sshkeyboard/__init__.py#L464

But the locking only happens on sys.stdin: 

   https://github.com/ollipal/sshkeyboard/blob/main/src/sshkeyboard/__init__.py#L343

My understanding is that Rich only deals with stdout, but perhaps I'm wrong.

**Comment by max-l** [comment]
I replaced sshkeyboard with https://github.com/magmax/python-readchar 

and I no longer have the problem

**Comment by max-l** [comment]
I'm goint to close the issue, since Rich is not likely at fault
