### ISSUE TITLE
[BUG] Rich doesn't work with pyrogram

### ISSUE THREAD

**Issue by hittiks** [Textualize/rich#2662]
I am writing a telegram userbot using the pyrogram library. And I have this code:

```
import config
import asyncio

from pyrogram import filters
from pyrogram.client import Client
from pyrogram.methods.utilities.idle import idle
from pyrogram.types.messages_and_media.message import Message

from rich.console import Console
from rich.traceback import install


console = Console(file=open("report.txt", "wt", encoding="utf-8"))
install(console=console, show_locals=True)


app = Client("my_account", session_string=config.APP_SESSION_STRING)


@app.on_message(filters.command("test", prefixes=".") & filters.user(config.OWNER_ID))
async def test_func(cl: Client, msg: Message):
    await msg.delete()

    print(3 + "s")


async def main():
        await app.start()
        
        # print(2 + "a")

        await idle()
        await app.stop(block=True)


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    run = loop.run_until_complete

    run(main())
```

If I uncomment print line in main, Rich correctly handle exception and write text to file report.txt. But if I leave this line commented (so code looks like above) and send command ".test" in telegram from my phone, the exception is printed to console with text like this:

```
unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "C:\Users\Skyline\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "c:/Users/Skyline/Desktop/tests/tg_test.py", line 24, in test_func
    print(3 + "s")
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```
So I don't understand if I'm doing something wrong or if it's a library incompatibility...

**Platform**
<details>
<summary>Click to expand</summary>

I'm using VS Code on Windows 10.

```
python -m rich.diagnose
```

```
┌───────────────────────── <class 'rich.console.Console'> ─────────────────────────┐
│ A high level console interface.                                                  │
│                                                                                  │
│ ┌──────────────────────────────────────────────────────────────────────────────┐ │
│ │ <console width=167 ColorSystem.WINDOWS>                                      │ │
│ └──────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                  │
│     color_system = 'windows'                                                     │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 46                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = True                                                          │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=167, height=46),             │
│                        legacy_windows=True,                                      │
│                        min_width=1,                                              │
│                        max_width=167,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=46,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=167, height=46)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 167                                                           │
└──────────────────────────────────────────────────────────────────────────────────┘
┌─── <class 'rich._windows.WindowsConsoleFeatures'> ────┐
│ Windows features available.                           │
│                                                       │
│ ┌───────────────────────────────────────────────────┐ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ └───────────────────────────────────────────────────┘ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
└───────────────────────────────────────────────────────┘
┌────── Environment Variables ───────┐
│ {                                  │
│     'TERM': None,                  │
│     'COLORTERM': None,             │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': None,          │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
└────────────────────────────────────┘
platform="Windows"
```

</details>

**Comment by hittiks** [comment]
Yes, I dug deeper into the pyrogram library, and all exceptions really were indeed caught there.
