### ISSUE TITLE
[BUG] Giving Text and invalid style does not raise MissingStyle

### ISSUE THREAD

**Issue by plannigan** [Textualize/rich#2796]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [X] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

When printing a text to a console, giving an invalid style name will raise the `MissingStyle` error. However, printing a `Text` instance with that same style name, results in the text being displayed without any styling applied. The same behavior exist for using the markup string form (because it is parsed into a `Text` instance).

```
Python 3.11.0 (main, Oct 26 2022, 05:13:43) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rich
>>> from rich.text import Text
>>> rich.get_console().print("hello", style="invalid_style")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.11/site-packages/rich/console.py", line 1699, in print
    render(renderable, render_options), self.get_style(style)
                                        ^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/rich/console.py", line 1476, in get_style
    raise errors.MissingStyle(
rich.errors.MissingStyle: Failed to get style 'invalid_style'; unable to parse 'invalid_style' as color; 'invalid_style' is not a valid color
>>> rich.get_console().print(Text("hello", style="invalid_style"))
hello
>>> rich.get_console().print("[invalid_style]hello[/invalid_style]")
hello
```

This seems to be caused by [this line](https://github.com/Textualize/rich/blob/b89d0362e8ebcb18902f0f0a206879f1829b5c0b/rich/text.py#L698), which forces the default style to be `Style.null()`.

**Platform**
<details>
<summary>Click to expand</summary>

```
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=138 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 59                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=138, height=59),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=138,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=59,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=138, height=59)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 138                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭─── <class 'rich._windows.WindowsConsoleFeatures'> ────╮
│ Windows features available.                           │
│                                                       │
│ ╭───────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ ╰───────────────────────────────────────────────────╯ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
╰───────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': 'xterm-256color',      │
│     'COLORTERM': 'truecolor',      │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': None,          │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Linux"
rich==13.3.1
```

</details>

**Comment by JuliaZhang7** [comment]
I also found this issue with the print function, for example, "print("Hello, [invalid]World[/invalid]!", ":dog:", locals())" will also not raise error and results in the text being displayed without any styling applied.

**Comment by JuliaZhang7** [comment]
Hello! We are a team of students from CMU and we'd like to work on this.
