### ISSUE TITLE
[BUG] Cannot use "on" in style with a custom Theme item

### ISSUE THREAD

**Issue by Predeactor** [Textualize/rich#2815]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

By using a custom theme (Which includes defaults or not, doesn't matter), if you try to use the "on" term in the style parameter, and attempt to use a color you have defined in your theme, Rich will says that it is not a valid color.

Here's an example:

```py
from rich.console import Console
from rich.theme import Theme

cons = Console(
    theme=Theme(
        {'title': 'cyan'}
    )
)
cons.print("[title]Hello world!")  # Work
cons.print("Hello world!", style="title")  # Works
cons.print("Hello world!", style="white on title")  # Exception here!

# But THIS will work:
cons.use_theme(Theme({'title': 'white on cyan'}))
cons.print("Hello world!", style="title")
```

**Exception**

```py
Traceback (most recent call last):
  File "a:\Projets\Fabricius\instance\personal_test.py", line 12, in <module>
    cons.print("Hello world!", style="white on title")  # Exception here!
  File "A:\Projets\Fabricius\.venv\lib\site-packages\rich\console.py", line 1699, in print
    render(renderable, render_options), self.get_style(style)
  File "A:\Projets\Fabricius\.venv\lib\site-packages\rich\console.py", line 1476, in get_style
    raise errors.MissingStyle(
rich.errors.MissingStyle: Failed to get style 'white on title'; unable to parse 'title' as background color; 'title' is not a valid color
```

I assume this is quite an expected behavior here, as it would be supposed to rather put "white on cyan" in my Theme class, but I find tricky to not be able to consider it as a valid color just because I want to put it as a background color.

**Platform**
<details>
<summary>Click to expand</summary>

- What platform (Win/Linux/Mac) are you running on?
> Windows 11, version 10.0.22621, build 22621

- What terminal software are you using?
> Visual Studio Code's builtin terminal, using powershell with oh-my-posh

```py
user ❯ python -m rich.diagnose
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=184 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 50                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=184, height=50),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=184,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=50,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=184, height=50)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 184                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭── <class 'rich._windows.WindowsConsoleFeatures'> ───╮
│ Windows features available.                         │
│                                                     │
│ ╭─────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=True, truecolor=True) │ │
│ ╰─────────────────────────────────────────────────╯ │
│                                                     │
│ truecolor = True                                    │
│        vt = True                                    │
╰─────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': None,                  │
│     'COLORTERM': 'truecolor',      │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': 'vscode',      │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Windows"
```

Rich is running version `12.6.0`.

</details>

**Comment by willmcgugan** [comment]
That's correct. Themes don't define colors, they define entire styles.
