### ISSUE TITLE
[BUG] Text.markup fails to escape backslashes

### ISSUE THREAD

**Issue by 1j01** [Textualize/rich#2993]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

(Related: https://github.com/Textualize/rich/issues/2987)

`Text.markup` fails to escape backslashes because `escape` only escapes backslashes contextually:
```py
>>> from rich.markup import escape
>>> escape("\\[foo]")
'\\\\\\[foo]'
>>> escape("\\") + escape("[foo]")
'\\\\[foo]'
>>> 
```
This leads to a failed round-trip from markup to markup:
```py
>>> from rich.text import Text
>>> Text.from_markup("[blue]\\\\[/blue]")
<text '\\' [Span(0, 1, 'blue')]>
>>> Text.from_markup("[blue]\\\\[/blue]").markup
'[blue]\\[/blue]'
>>> Text.from_markup("[blue]\\[/blue]")
<text '[/blue]' [Span(0, 7, 'blue')]>
>>> Text.from_markup("[blue]\\[/blue]").markup
'[blue]\\[/blue][/blue]'
```
or even errors about mismatched tags:
```py
>>> markup = Text.from_markup("[rgb(255,255,0) on rgb(255,0,0)]\\\\[rgb(0,0,0) on rgb(0,255,0)][/rgb(255,2
55,0) on rgb(255,0,0)]0[/rgb(0,0,0) on rgb(0,255,0)]").markup
>>> markup
'[rgb(255,255,0) on rgb(255,0,0)]\\[rgb(0,0,0) on rgb(0,255,0)][/rgb(255,255,0) on rgb(255,0,0)]0[/rgb(0,0,0) on rgb(0,255,0)]'
>>> Text.from_markup(markup)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/io/Projects/textual-paint/.venv/lib/python3.10/site-packages/rich/text.py", line 268, in from_markup
    rendered_text = render(text, style, emoji=emoji, emoji_variant=emoji_variant)
  File "/home/io/Projects/textual-paint/.venv/lib/python3.10/site-packages/rich/markup.py", line 161, in render
    raise MarkupError(
rich.errors.MarkupError: closing tag '[/rgb(0,0,0) on rgb(0,255,0)]' at position 95 doesn't match any open tag
```

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=106 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 30                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=106, height=30),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=106,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=30,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=106, height=30)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 106                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭─── <class 'rich._windows.WindowsConsoleFeatures'> ────╮
│ Windows features available.                           │
│                                                       │
│ ╭───────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ ╰───────────────────────────────────────────────────╯ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
╰───────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': 'xterm-256color',      │
│     'COLORTERM': 'truecolor',      │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': 'vscode',      │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Linux"
rich==13.3.5
```

If you're using Rich in a Jupyter Notebook, run the following snippet in a cell
and paste the output in your bug report.

```python
from rich.diagnose import report
report()
```

</details>

**Comment by calestyo** [comment]
@willmcgugan Any news on this?

I've been trying to come up with a PR for #4040, but right now this seems impossible because the escaping is broken and cannot be properly reversed.

I think the fixes (2dc8398afa1a78e7bc4d3d17905e5fd2c82e1932 and 58f54ca7a391c4f12a1737128e95757cc15587f9) for #2987 are inclomplete, which becomes already clear because:
https://github.com/Textualize/rich/blob/fc41075a3206d2a5fd846c6f41c4d2becab814fa/rich/markup.py#L67-L68
is not reversible.

Take e.g.:
```
>>> value = r"C:\\"
>>> print(value)
C:\\
>>> rich.print(f"[red]{value}[/red]")
C:\
>>> rich.print(f"[red]{escape(value)}[/red]")
C:\
```

What about simply quoting **every** trailing backslash?
I'd have made a PR but apparently contributions are not welcome and PRs disabled? o.O
Well should you want it nevertheless, here’s the branch https://github.com/calestyo/rich/tree/fix-escaping .

**Comment by calestyo** [comment]
I’ve added two more commits to the branch, which would implement what I’ve asked for in #4040 (see there for further details about the extra commits).
