### ISSUE TITLE
[BUG]  Inconsistent traceback logging

### ISSUE THREAD

**Issue by ibro45** [Textualize/rich#3269]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

I define my `rich` + `loguru` setup [here](https://github.com/project-lighter/lighter/blob/51a3c6656a474f2351cc55b1e09385e01e3ce960/lighter/logging.py#L33), and I set it up first thing in the [`__init__.py` of my framework.](https://github.com/project-lighter/lighter/blob/51a3c6656a474f2351cc55b1e09385e01e3ce960/lighter/__init__.py#L3)

It appeared to work alright when a simpler exception chain occurred:
![image](https://github.com/Textualize/rich/assets/18015788/f3933e85-db72-4102-95b2-082da0247df3)

However, a more complex issue seems to be outputting tracebacks very inconsistently. First, it prints it out as if no formatting was used. Then, a small `rich` traceback is displayed. Finally, a long traceback was logged with `rich,` but not as a traceback, but rather as a rich console print, I think.

I am trying to figure out the issue, and any expert intuition would be appreciated. The images below show how it looks; the full trace is further below.

<img width="870" alt="image" src="https://github.com/Textualize/rich/assets/18015788/9a5e6f3a-9232-46ac-8a0d-b40d2d6cea73">
<img width="870" alt="image" src="https://github.com/Textualize/rich/assets/18015788/1351f8c8-848b-4a89-b49b-810a70a88132">

**Full trace**
<details>
<summary>Click to expand</summary>

```bash
2024/02/02 16:21:14.889  |  ⚠️  WARNING   |  No seed found, seed set to 3793871955                                                 rank_zero.py:74
Seed set to 3793871955
2024/02/02 16:21:14.999  |  ℹ️  INFO      |  /mnt/ssd1/rogueone/ibro/lighter/projects/lighter-nsclc-segmentation imported as dynamic_imports.py:76
'project' module.                                                                                                                                
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
2024/02/02 16:21:16.092  |  ℹ️  INFO      |  Checkpoint loaded successfully.                                                          model.py:120
2024/02/02 16:21:16.101  |  ⚠️  WARNING   |  required package for reader ITKReader is not installed, or the version doesn't match     array.py:205
requirement.                                                                                                                                     
2024/02/02 16:21:16.103  |  ⚠️  WARNING   |  monai.transforms.croppad.dictionary CropForegroundd.__init__:allow_smaller:     deprecate_utils.py:38
Current default value of argument `allow_smaller=True` has been deprecated since version 1.2. It will be changed to                              
`allow_smaller=False` in version 1.5.                                                                                                            
You are using a CUDA device ('NVIDIA RTX A6000') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
2024/02/02 16:21:19.197  |  ⚠️  WARNING   |  /mnt/ssd1/rogueone/ibro/CT_FM/ct_fm_nsclc/predictions/RADIO/random_init_100 already        base.py:88
exists, existing predictions will be overwritten.                                                                                                
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [1]
2024/02/02 16:21:19.261  |  ℹ️  INFO      |  Setting the 'predict' mode dataloader to batch size of 1 because an inferer is          system.py:299
provided.                                                                                                                                        

Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/aim/bin/lighter", line 8, in <module>
    sys.exit(interface())
  File "/mnt/ssd1/rogueone/ibro/lighter/lighter/utils/cli.py", line 23, in interface
    fire.Fire(commands)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/fire/core.py", line 566, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/ssd1/rogueone/ibro/lighter/lighter/utils/runner.py", line 70, in run_trainer_method
    getattr(trainer, method)(system)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in predict
    return call._call_and_handle_interrupt(
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 903, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1030, in _run_stage
    return self.predict_loop.run()
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/loops/prediction_loop.py", line 119, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 127, in __next__
    batch = super().__next__()
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 56, in __next__
    batch = next(self.iterator)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py", line 326, in __next__
    out = next(self._iterator)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py", line 132, in __next__
    out = next(self.iterators[0])
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/io/dictionary.py", line 162, in __call__
    data = self._loader(d[key], reader)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/io/array.py", line 274, in __call__
    raise RuntimeError(
RuntimeError: LoadImage cannot find a suitable reader for file: /mnt/ssd1/rogueone/ibro/Datasets/RADIO/R01-049/CT/R01-049.nrrd.
    Please install the reader libraries, see also the installation instructions:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies.
   The current registered: [<monai.data.image_reader.NumpyReader object at 0x7f07080ca9b0>, <monai.data.image_reader.PILReader object at 0x7f07080ca8f0>].
Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/io/array.py", line 259, in __call__
    img = reader.read(filename)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/data/image_reader.py", line 1165, in read
    img = PILImage.open(name, **kwargs_)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/PIL/Image.py", line 3280, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/mnt/ssd1/rogueone/ibro/Datasets/RADIO/R01-049/CT/R01-049.nrrd'

Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/numpy/lib/npyio.py", line 465, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: unpickling stack underflow

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/io/array.py", line 259, in __call__
    img = reader.read(filename)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/data/image_reader.py", line 1068, in read
    img = np.load(name, allow_pickle=True, **kwargs_)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/numpy/lib/npyio.py", line 467, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file '/mnt/ssd1/rogueone/ibro/Datasets/RADIO/R01-049/CT/R01-049.nrrd' as a pickle


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/compose.py", line 335, in __call__
    result = execute_compose(
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/compose.py", line 111, in execute_compose
    data = apply_transform(
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x7f07080cb760>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/data/dataset.py", line 112, in __getitem__
    return self._transform(index)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/data/dataset.py", line 98, in _transform
    return apply_transform(self.transform, data_i) if self.transform is not None else data_i
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7f07080c9bd0>

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ibrahim/anaconda3/envs/aim/bin/lighter:8 in <module>                                       │
│                                                                                                  │
│   5 from lighter.utils.cli import interface                                                      │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(interface())                                                                    │
│   9                                                                                              │
│                                                                                                  │
│ /mnt/ssd1/rogueone/ibro/lighter/lighter/utils/cli.py:23 in interface                             │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/fire/core.py:141 in Fire           │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/fire/core.py:566 in _Fire          │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/fire/core.py:691 in                │
│ _CallAndUpdateTrace                                                                              │
│                                                                                                  │
│ /mnt/ssd1/rogueone/ibro/lighter/lighter/utils/runner.py:70 in run_trainer_method                 │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer. │
│ py:864 in predict                                                                                │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py: │
│ 44 in _call_and_handle_interrupt                                                                 │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer. │
│ py:903 in _predict_impl                                                                          │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer. │
│ py:989 in _run                                                                                   │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer. │
│ py:1030 in _run_stage                                                                            │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/loops/utilities. │
│ py:182 in _decorator                                                                             │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/loops/prediction │
│ _loop.py:119 in run                                                                              │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.p │
│ y:127 in __next__                                                                                │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.p │
│ y:56 in __next__                                                                                 │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/utilities/combin │
│ ed_loader.py:326 in __next__                                                                     │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/pytorch_lightning/utilities/combin │
│ ed_loader.py:132 in __next__                                                                     │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/torch/utils/data/dataloader.py:631 │
│ in __next__                                                                                      │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/torch/utils/data/dataloader.py:134 │
│ 6 in _next_data                                                                                  │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/torch/utils/data/dataloader.py:137 │
│ 2 in _process_data                                                                               │
│                                                                                                  │
│ /home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/torch/_utils.py:722 in reraise     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/io/dictionary.py", line 162, in __call__
    data = self._loader(d[key], reader)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/io/array.py", line 274, in __call__
    raise RuntimeError(
RuntimeError: LoadImage cannot find a suitable reader for file: /mnt/ssd1/rogueone/ibro/Datasets/RADIO/R01-049/CT/R01-049.nrrd.
    Please install the reader libraries, see also the installation instructions:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies.
   The current registered: [<monai.data.image_reader.NumpyReader object at 0x7f07080ca9b0>, <monai.data.image_reader.PILReader object at 
0x7f07080ca8f0>].
Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/io/array.py", line 259, in __call__
    img = reader.read(filename)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/data/image_reader.py", line 1165, in read
    img = PILImage.open(name, **kwargs_)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/PIL/Image.py", line 3280, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/mnt/ssd1/rogueone/ibro/Datasets/RADIO/R01-049/CT/R01-049.nrrd'

Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/numpy/lib/npyio.py", line 465, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: unpickling stack underflow

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/io/array.py", line 259, in __call__
    img = reader.read(filename)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/data/image_reader.py", line 1068, in read
    img = np.load(name, allow_pickle=True, **kwargs_)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/numpy/lib/npyio.py", line 467, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file '/mnt/ssd1/rogueone/ibro/Datasets/RADIO/R01-049/CT/R01-049.nrrd' as a pickle


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/compose.py", line 335, in __call__
    result = execute_compose(
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/compose.py", line 111, in execute_compose
    data = apply_transform(
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x7f07080cb760>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/data/dataset.py", line 112, in __getitem__
    return self._transform(index)
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/data/dataset.py", line 98, in _transform
    return apply_transform(self.transform, data_i) if self.transform is not None else data_i
  File "/home/ibrahim/anaconda3/envs/aim/lib/python3.10/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7f07080c9bd0>
```

</details>

**Platform**
<details>
<summary>Click to expand</summary>

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"

Using `bash`, `rich==13.7.0`, `loguru==0.6.0`.

</details>

**Comment by ibro45** [comment]
It's probably due to the parallel nature of the PyTorch Dataloader when multiple workers are used. I haven't found a solution yet.
