### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'typing'

### ISSUE THREAD

**Issue by AlanMW** [Textualize/rich#3334]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**
I am getting the following error when attempting to use rich:
`ModuleNotFoundError: No module named 'typing'`

```
File "/home/user/Text_Gen/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/rich/__init__.py", line 4, in <module>
  from typing import IO, TYPE_CHECKING, Any, Callable, Optional, Union
ModuleNotFoundError: No module named 'typing'
```

**Platform**
<details>
<summary>Click to expand</summary>

Linux, ssh from windows cmd prompt

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
```

```
(/home/user/Text_Gen/text-generation-webui-main/installer_files/env) user@userserver:~$ python -m rich.diagnose
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/user/Text_Gen/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/rich/__init__.py", line 4, in <module>
    from typing import IO, TYPE_CHECKING, Any, Callable, Optional, Union
ModuleNotFoundError: No module named 'typing'
```

```
(/home/user/Text_Gen/text-generation-webui-main/installer_files/env) user@userserver:~$ pip freeze | grep rich
Traceback (most recent call last):
  File "/home/user/Text_Gen/text-generation-webui-main/installer_files/env/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/home/user/Text_Gen/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/pip/__init__.py", line 1, in <module>
    from typing import List, Optional
ModuleNotFoundError: No module named 'typing'
```

</details>

**Comment by TomJGooding** [comment]
I'm afraid you have a problem with your Python environment, this isn't a Rich issue. Notice that trying to run just the `pip freeze` command gave you the same error.

**Comment by willmcgugan** [comment]
The `typing` module is in the standard library. If that doesn't exist then something is amis with your environment, as Tom pointed out. Try recreating your virtual environement?
