### ISSUE TITLE
`RichHandler` does not handle log formatting exceptions

### ISSUE THREAD

**Issue by snejus** [Textualize/rich#3536]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

`RichHandler` does not handle exceptions raised while formatting the log message, unlike
default builtin Python handlers.

**Simple example**

Below I set up the logger with `RichHandler` and provide bad arguments to the `log.warning` call.

```python
>>> import logging
>>> from rich.logging import RichHandler

>>> log = logging.getLogger(__name__)
>>> log.handlers = [RichHandler()]

>>> log.warning("{bad}", 123)
... print("logic continues")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[12], line 1
----> 1 log.warning("{bad}", 123)
      2 print("logic continues")

...

File ~/.local/share/pyenv/versions/3.8.19/lib/python3.8/logging/__init__.py:373, in LogRecord.getMessage(self)
    371 msg = str(self.msg)
    372 if self.args:
--> 373     msg = msg % self.args
    374 return msg

TypeError: not all arguments converted during string formatting

>>>
```

I expected the logic to continue running with message **logic continues** printed. Compare
this with the default behaviour:

```python
>>> import logging
>>> log = logging.getLogger(__name__)

>>> log.handlers = [logging.StreamHandler()]

>>> log.warning("{bad}", 123)
... print("logic continues")
--- Logging error ---
Traceback (most recent call last):
  File "/home/sarunas/.local/share/pyenv/versions/3.8.19/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/home/sarunas/.local/share/pyenv/versions/3.8.19/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)

...

  File "/media/poetry/virtualenvs/rich-tables-clqIuwIl-py3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-ee55d4d922a6>", line 1, in <module>
    log.warning("{bad}", 123)
Message: '{bad}'
Arguments: (123,)
logic continues

>>>
```

Here the exception got handled and my logic continued running with the message being printed.

**The cause**

I had a quick glance at `RichHandler` implementation and compared it with `StreamHandler`. I think the issue lies in `emit` method implementation:

```python
class StreamHandler(Handler):
    ...
    def emit(self, record):
        try:
            msg = self.format(record)
            stream = self.stream
            # issue 35046: merged two stream.writes into one.
            stream.write(msg + self.terminator)
            self.flush()
        except RecursionError:  # See issue 36272
            raise
        except Exception:
            self.handleError(record)
```

and 

```python
class RichHandler(Handler):
    ...
    def emit(self, record: LogRecord) -> None:
        """Invoked by logging."""
        message = self.format(record)
        traceback = None
        ...
```

In `StreamHandler`, the `self.format(record)` call is tucked under the `try` statement while in `RichHandler` is is not.

**Comment by jakub-mrow** [comment]
Hi, I have created a PR for this issue, would love to contribute!
